### ISSUE TITLE
Shouldn't this be called something else?

### ISSUE THREAD

**Issue by Demonstrandum** [emil-petras/strapi-blurhash#10]
Shouldn't this be called `strapi-plaiceholder` or something, since it doesn't use the original [woltapp/blurhash](https://github.com/woltapp/blurhash), but the [joe-bell/plaiceholder](https://github.com/joe-bell/plaiceholder) algorithm?

This is also not clearly mentioned anywhere. And is especially inconvenient since plaiceholder does not enable client side (browser) rendering.

**Comment by emil-petras** [comment]
You are right. I've reworked this to use the wolt/blurhash in the new version.
