### ISSUE TITLE
Issue with Image Uploads and White Screen on Strapi Versions 4.13.2 and Above

### ISSUE THREAD

**Issue by kyryloren** [emil-petras/strapi-blurhash#13]
**Issue Summary:**
On versions of Strapi 4.13.2 and up, attempting to upload new images to the media library leads to a white screen, rendering no images correctly. This issue is accompanied by a console error message: `Failed to construct 'URL': Invalid URL`. My Strapi application is connected to a Postgres database.

**Steps to reproduce:**
Upgrade Strapi to version 4.13.2 or a later version.
Attempt to upload a new image to the media library.

**Expected Behavior:**
The image should be uploaded to the media library without any issues, and it should be rendered correctly on the screen.

**Possible Solutions/Workarounds Tried:**
I've attempted to find a solution but haven't been successful so far. Downgrading the application to version 4.13.1 and creating a new database is a workaround, but it's not an ideal solution.

![Screenshot of error](https://i.imgur.com/DVlqACX.png)

**Comment by emil-petras** [comment]
Do you still have this problem? If yes, can you provide the strapi logs ?

**Comment by GraemeFulton** [comment]
I think here: https://github.com/emil-petras/strapi-blurhash/blob/296bd8b2fd4736df612694820105d9273b2510b6/server/bootstrap.js#L8

If you put:
`if(!data || !data.mime) return;`

that would fix this issue..it is running on beforeCreate/beforeUpdate, so anything can trigger this, and maybe no url is present (e.g., if you just update the alt text alone)
