### ISSUE TITLE
Bump nodejs to 20

### ISSUE THREAD

**Issue by CodeDruid13** [emil-petras/strapi-blurhash#14]
error strapi-blurhash@1.1.1: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.9.0"
[2023-10-26 17:53:26] │ error Found incompatible module.

This is on the latest strapi.

Please remove the Node version check to make it easier for future updates

**Comment by emil-petras** [comment]
I've removed the version check in the new version.
