### ISSUE TITLE
Does this plugin work for existing images?

### ISSUE THREAD

**Issue by niklasfjeldberg** [emil-petras/strapi-blurhash#2]

**Comment by emil-petras** [comment]
No, the images need to be uploaded in order to generate the blurhash value.

This feature is planned in the future. So that the blurhash gets generated on save.

**Comment by wvovaw** [comment]
For those of You who has a lot of media and don't want to update every image manually:

```js
// ~/src/index.js
'use strict';

module.exports = {
  
  register() { },

  bootstrap() {
    const updateAllMediaFiles = async () => {

      const uploads = await strapi.query('plugin::upload.file').findMany();
      for (const item of uploads) {
        if ((item.mime && item.mime.startsWith('image/') && !item.blurhash)) {
          const blurhash = await strapi.plugin('strapi-blurhash').service('blurhash').generateBlurhash(item.url);
          await strapi.db.query('plugin::upload.file').update({
            where: { id: item.id },
            data: {
              blurhash
            },
          });
        }
      }
      strapi.log.debug("Finished generating blurhash for the library");
    };

    updateAllMediaFiles();
  },
};
```

Just run it and wait some time untill the job is done. Once its done just remove the code

**Comment by mauriciabad** [comment]
Awesome @wvovaw! 

Took your code and created a PR implementing it! #12 

It's my first time developing in strapi, so any help on that PR would be appreciated.

**Comment by moda-team** [comment]
> For those of You who has a lot of media and don't want to update every image manually:
> 
> ```js
> // ~/src/index.js
> 'use strict';
> 
> module.exports = {
>   
>   register() { },
> 
>   bootstrap() {
>     const updateAllMediaFiles = async () => {
> 
>       const uploads = await strapi.query('plugin::upload.file').findMany();
>       for (const item of uploads) {
>         if ((item.mime && item.mime.startsWith('image/') && !item.blurhash)) {
>           const blurhash = await strapi.plugin('strapi-blurhash').service('blurhash').generateBlurhash(item.url);
>           await strapi.db.query('plugin::upload.file').update({
>             where: { id: item.id },
>             data: {
>               blurhash
>             },
>           });
>         }
>       }
>       strapi.log.debug("Finished generating blurhash for the library");
>     };
> 
>     updateAllMediaFiles();
>   },
> };
> ```
> 
> Just run it and wait some time untill the job is done. Once its done just remove the code

How do I run this code though? Does it run on build time?

**Comment by konipro** [comment]
Solution for the error ‘TypeError: Only absolute URLs are supported’:

`let url = "https://strapi.diestadt.app" + item.url`

**Comment by konipro** [comment]
> > For those of You who has a lot of media and don't want to update every image manually:
> > ```js
> > // ~/src/index.js
> > 'use strict';
> > 
> > module.exports = {
> >   
> >   register() { },
> > 
> >   bootstrap() {
> >     const updateAllMediaFiles = async () => {
> > 
> >       const uploads = await strapi.query('plugin::upload.file').findMany();
> >       for (const item of uploads) {
> >         if ((item.mime && item.mime.startsWith('image/') && !item.blurhash)) {
> >           const blurhash = await strapi.plugin('strapi-blurhash').service('blurhash').generateBlurhash(item.url);
> >           await strapi.db.query('plugin::upload.file').update({
> >             where: { id: item.id },
> >             data: {
> >               blurhash
> >             },
> >           });
> >         }
> >       }
> >       strapi.log.debug("Finished generating blurhash for the library");
> >     };
> > 
> >     updateAllMediaFiles();
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just run it and wait some time untill the job is done. Once its done just remove the code
> 
> How do I run this code though? Does it run automatically on build time?

Yes exactly, simply overwrite the code from index.js for a short time. The bootstrap() function is executed shortly after Strapi is started.  You don't have to create a build or anything, just start strapi as usual (e.g. ‘npm run develop’)

**Comment by emil-petras** [comment]
> Small improvement, intercept webp files:
> 
> `if (( item.mime && item.mime.startsWith('image/') && !item.blurhash && !item.url.endsWith('.webp') //Add this line )) `

Good catch. The new version 1.2.1 uses sharp now, this solves the webp issue.

> Solution for the error ‘TypeError: Only absolute URLs are supported’:
> 
> `let url = "https://strapi-url.com" + item.url`

When do you get this error? Can you copy the log and/or give more info?

**Comment by maximehamou** [comment]
Solution for the error `Could not load the "sharp" module using the darwin-x64` :

```
yarn add sharp --ignore-engines
```

Also, to use this, I have to replace `item.mime.startsWith('image/')` by `item.mime.startsWith('uploads')` :

> ```js
> // ~/src/index.js
> 'use strict';
> 
> module.exports = {
>   
>   register() { },
> 
>   bootstrap() {
>     const updateAllMediaFiles = async () => {
> 
>       const uploads = await strapi.query('plugin::upload.file').findMany();
>       for (const item of uploads) {
>         if ((item.mime && item.mime.startsWith('image/') && !item.blurhash)) {
>           const blurhash = await strapi.plugin('strapi-blurhash').service('blurhash').generateBlurhash(item.url);
>           await strapi.db.query('plugin::upload.file').update({
>             where: { id: item.id },
>             data: {
>               blurhash
>             },
>           });
>         }
>       }
>       strapi.log.debug("Finished generating blurhash for the library");
>     };
> 
>     updateAllMediaFiles();
>   },
> };
> ```
