### ISSUE TITLE
Could not load the "sharp" module

### ISSUE THREAD

**Issue by maximehamou** [emil-petras/strapi-blurhash#20]
Hello,
I have this error in local (MacOS) and in production (Debian) :
```
[2024-05-23 18:13:47.266] debug: ⛔️ Server wasn't able to start properly.
[2024-05-23 18:13:47.267] error: Could not load js config file /app/node_modules/strapi-blurhash/strapi-server.js: Could not load the "sharp" module using the linux-x64 runtime
```
I think there is an issue in the way that the plugin uses sharp.

Thank you for your help.

**Comment by emil-petras** [comment]
On mac, try

brew install pkg-config
brew install libvips

On debian:
sudo apt-get update
sudo apt-get install -y build-essential
sudo apt-get install -y libvips-dev

**Comment by maximehamou** [comment]
But is it normal that it always happen using the plugin if I not do that?

**Comment by emil-petras** [comment]
I will try to find a way for this to be solved automatically during installation.

**Comment by maximehamou** [comment]
Ok thank you ! Because there is a really big quantity of packages in `libvips-dev` !

**Comment by maximehamou** [comment]
> EDIT : installing these packages does not solve the problem.

So, do you have any other ideas? Thanks!

**Comment by emil-petras** [comment]
I've removed the sharp dependency in the new version.

**Comment by maximehamou** [comment]
There is now this error :
```
Error: Could not load js config file
/Users/Maxime/Desktop/Projets_de_code/zakine-avocats.fr/backend/node_modules/strapi-blurhash/strapi-server.js: Cannot find module 'canvas' 
```

**Comment by emil-petras** [comment]
@maximehamou 
sudo apt-get update
sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
npm install canvas
npm list canvas
