### ISSUE TITLE
Issue with plugin version deployed on NPM

### ISSUE THREAD

**Issue by MDSilviu** [emil-petras/strapi-blurhash#22]
The latest version published on npm is 1.3.0 that's missing from github and also has an error
Error: Could not load js config file  \node_modules\strapi-blurhash\strapi-server.js: Cannot find  module 'canvas'

**Comment by emersonart** [comment]
I tried to install: npm i canvas.

An error occurred, only the error type changed.

`Could not load js config file ...\node_modules\strapi-blurhash\strapi-server.js: error: 127\\?\...\node_modules\canvas\build\Release\canvas.node`

**Comment by emil-petras** [comment]
`sudo apt-get update
sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
npm install canvas`

Should work
