### ISSUE TITLE
Compatible with Strapi V5?

### ISSUE THREAD

**Issue by frankieboxx** [emil-petras/strapi-blurhash#23]
During compiling Strapi V5 an error occurs :

npm error Could not resolve dependency:
npm error peer @strapi/strapi@"^4.0.0" from strapi-blurhash@1.3.0
npm error node_modules/strapi-blurhash
npm error   strapi-blurhash@"1.3

Is there a possibility to use the plugin on Strapi 5.0?

**Comment by vellnes** [comment]
@emil-petras Hi, can you update the plugin to be compatible with version 5?
Something like this.
https://www.npmjs.com/package/strapi-v5-blurhash?activeTab=code

**Comment by emil-petras** [comment]
@vellnes I will do it these days, when I find the time.

**Comment by emil-petras** [comment]
I updated it. The version 2.0.0 supports strapi v5

**Comment by frankieboxx** [comment]
Hi, thanks for informing me.
Unfortunately, I am still getting errors when I install the plugin :

d:\tendo.hr\strapiV5.tendo.hr\node_modules\strapi-blurhash\strapi-server.js:
The specified procedure could      │
d:\tendo.hr\strapiV5.tendo.hr\node_modules\canvas\build\Release\canvas.node


[image: image.png]

Using Strapi :
Version            │ 5.5.0 (node v20.9.0)
With TypeScript support.

The Strapi database is empty because I am trying to update from V4 to V5.
And idea what might cause this problem?

Regards, Frano.
